name: FreedomOpMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 7.2.8
description: Plugin for the FreedomOp server.
softdepend: [BukkitTelnet, LibsDisguises, WorldEdit, Essentials]
authors: [Madgeek1450, DarthSalamon]

# plugin.yml is no longer used to define commands.
